name: Android CI

on:
  pull_request:
    branches: 
    - master
    - dev
  
  workflow_dispatch:

jobs:
  build_test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
#     - name: Build with Gradle
#       env:
#         TEST_TOKEN_KEY: ${{ secrets.TEST_TOKEN_KEY }}
#       run: ./gradlew build
    - name: Run tests
      env:
        TEST_TOKEN_KEY: ${{ secrets.TEST_TOKEN_KEY }}
      uses: reactivecircus/android-emulator-runner@v2
      with:
         api-level: 29
         script: ./gradlew connectedCheck
